# 从项目根 .env 生成 mobile/src/config/bundledDefaults.ts（打包进 APK 的默认 Key）
$ErrorActionPreference = "Stop"
$MobileRoot = Split-Path $PSScriptRoot -Parent
$ProjectRoot = Split-Path $MobileRoot -Parent
$EnvFile = Join-Path $ProjectRoot ".env"
$OutFile = Join-Path $MobileRoot "src\config\bundledDefaults.ts"

function Parse-DotEnv($path) {
    $map = @{}
    if (-not (Test-Path $path)) { return $map }
    Get-Content $path -Encoding UTF8 | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) { return }
        $key = $line.Substring(0, $eq).Trim()
        $val = $line.Substring($eq + 1).Trim()
        if ($val.StartsWith('"') -and $val.EndsWith('"')) { $val = $val.Substring(1, $val.Length - 2) }
        $map[$key] = $val
    }
    return $map
}

function Esc([string]$s) {
    if ($null -eq $s) { return "" }
    return ($s -replace "\\", "\\\\" -replace "'", "\\'")
}

$envMap = Parse-DotEnv $EnvFile

$defaults = @{
    apiKey            = $envMap["API_KEY"]
    apiEndpoint       = if ($envMap["API_ENDPOINT"]) { $envMap["API_ENDPOINT"] } else { "https://dashscope.aliyuncs.com/compatible-mode/v1" }
    textModel         = if ($envMap["TEXT_MODEL"]) { $envMap["TEXT_MODEL"] } else { "qwen-plus" }
    imageModel        = if ($envMap["TONGYI_IMAGE_MODEL"]) { $envMap["TONGYI_IMAGE_MODEL"] } elseif ($envMap["IMAGE_MODEL"]) { $envMap["IMAGE_MODEL"] } else { "wan2.6-t2i" }
    arkApiKey         = $envMap["ARK_API_KEY"]
    arkBaseUrl        = if ($envMap["ARK_BASE_URL"]) { $envMap["ARK_BASE_URL"] } else { "https://ark.cn-beijing.volces.com/api/v3" }
    doubaoModel       = if ($envMap["DOUBAO_IMAGE_MODEL"]) { $envMap["DOUBAO_IMAGE_MODEL"] } else { "doubao-seedream-4-5-251128" }
    seedanceApiKey    = if ($envMap["VOLC_SEEDANCE_API_KEY"]) { $envMap["VOLC_SEEDANCE_API_KEY"] } elseif ($envMap["SEEDANCE_API_KEY"]) { $envMap["SEEDANCE_API_KEY"] } else { "" }
    seedanceUrl       = if ($envMap["VOLC_SEEDANCE20_URL"]) { $envMap["VOLC_SEEDANCE20_URL"] } else { "https://getways-jumu.zeelin.cn/v1/video/generations" }
    seedanceResultUrl = if ($envMap["VOLC_SEEDANCE20_RESULT_URL"]) { $envMap["VOLC_SEEDANCE20_RESULT_URL"] } else { "https://getways-jumu.zeelin.cn/v1/video/result" }
}

if (-not $defaults.seedanceApiKey -and $env:VOLC_SEEDANCE_API_KEY) {
    $defaults.seedanceApiKey = $env:VOLC_SEEDANCE_API_KEY
}

$content = @"
/** Auto-generated by scripts/sync-default-settings.ps1 from .env — do not edit manually */
export const BUNDLED_DEFAULTS = {
  apiKey: '$($defaults.apiKey | ForEach-Object { Esc $_ })',
  apiEndpoint: '$($defaults.apiEndpoint | ForEach-Object { Esc $_ })',
  textModel: '$($defaults.textModel | ForEach-Object { Esc $_ })',
  imageModel: '$($defaults.imageModel | ForEach-Object { Esc $_ })',
  arkApiKey: '$($defaults.arkApiKey | ForEach-Object { Esc $_ })',
  arkBaseUrl: '$($defaults.arkBaseUrl | ForEach-Object { Esc $_ })',
  doubaoModel: '$($defaults.doubaoModel | ForEach-Object { Esc $_ })',
  seedanceApiKey: '$($defaults.seedanceApiKey | ForEach-Object { Esc $_ })',
  seedanceUrl: '$($defaults.seedanceUrl | ForEach-Object { Esc $_ })',
  seedanceResultUrl: '$($defaults.seedanceResultUrl | ForEach-Object { Esc $_ })',
} as const;
"@

Set-Content -Path $OutFile -Value $content -Encoding UTF8
Write-Host "Generated $OutFile"
if (-not $defaults.apiKey) { Write-Host "WARN: API_KEY empty in .env" -ForegroundColor Yellow }
if (-not $defaults.seedanceApiKey) { Write-Host "WARN: VOLC_SEEDANCE_API_KEY not set (anime video needs Zeelin key)" -ForegroundColor Yellow }
